//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.GPWDataService"/> </summary
    public sealed class GPWDataServiceClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the IsMicroServiceReady method on the GPWDataService microservice
        /// <see cref="Beamable.Server.GPWDataService.IsMicroServiceReady"/>
        /// </summary>
        public Beamable.Common.Promise<bool> IsMicroServiceReady()
        {
            string[] serializedFields = new string[0];
            return this.Request<bool>("GPWDataService", "IsMicroServiceReady", serializedFields);
        }
        
        /// <summary>
        /// Call the IsMicroStorageReady method on the GPWDataService microservice
        /// <see cref="Beamable.Server.GPWDataService.IsMicroStorageReady"/>
        /// </summary>
        public Beamable.Common.Promise<bool> IsMicroStorageReady()
        {
            string[] serializedFields = new string[0];
            return this.Request<bool>("GPWDataService", "IsMicroStorageReady", serializedFields);
        }
        
        /// <summary>
        /// Call the HasLocationContentViews method on the GPWDataService microservice
        /// <see cref="Beamable.Server.GPWDataService.HasLocationContentViews"/>
        /// </summary>
        public Beamable.Common.Promise<bool> HasLocationContentViews()
        {
            string[] serializedFields = new string[0];
            return this.Request<bool>("GPWDataService", "HasLocationContentViews", serializedFields);
        }
        
        /// <summary>
        /// Call the GetLocationContentViews method on the GPWDataService microservice
        /// <see cref="Beamable.Server.GPWDataService.GetLocationContentViews"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Samples.GPW.Data.LocationContentViewCollection> GetLocationContentViews()
        {
            string[] serializedFields = new string[0];
            return this.Request<Beamable.Samples.GPW.Data.LocationContentViewCollection>("GPWDataService", "GetLocationContentViews", serializedFields);
        }
        
        /// <summary>
        /// Call the CreateLocationContentViews method on the GPWDataService microservice
        /// <see cref="Beamable.Server.GPWDataService.CreateLocationContentViews"/>
        /// </summary>
        public Beamable.Common.Promise<bool> CreateLocationContentViews(System.Collections.Generic.List<Beamable.Samples.GPW.Data.LocationData> locationDatas, System.Collections.Generic.List<Beamable.Samples.GPW.Data.ProductData> productDatas)
        {
            string serialized_locationDatas = this.SerializeArgument<System.Collections.Generic.List<Beamable.Samples.GPW.Data.LocationData>>(locationDatas);
            string serialized_productDatas = this.SerializeArgument<System.Collections.Generic.List<Beamable.Samples.GPW.Data.ProductData>>(productDatas);
            string[] serializedFields = new string[] {
                    serialized_locationDatas,
                    serialized_productDatas};
            return this.Request<bool>("GPWDataService", "CreateLocationContentViews", serializedFields);
        }
    }
}
